development: &DEFAULTS
  bucket: "odiun_staging"
  access_key_id: ""
  secret_access_key: ""

test:
  <<: *DEFAULTS
  bucket: "odiun_staging"

ci:
  <<: *DEFAULTS
  bucket: "odiun_staging"

production: &production
  bucket: "odiun_staging"
  access_key_id: ""
  secret_access_key: ""

staging:
  <<: *production