development: &DEFAULTS
  bucket: "odiun-staging"
  access_key_id: "AKIAIOREVTQRIDMV2YHA"
  secret_access_key: "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"

test:
  <<: *DEFAULTS
  bucket: "odiun-staging"

ci:
  <<: *DEFAULTS
  bucket: "odiun-staging"

production: &production
  bucket: "odiun-staging"
  access_key_id: "AKIAIOREVTQRIDMV2YHA"
  secret_access_key: "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"

staging:
  <<: *production